//
// Copyright (c) 2018-2026 PADL Software Pty Ltd
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
//

import XCTest
@testable import MOM

/// Golden wire-format tests captured from the original C Surrogate
/// implementation (main @ 967c66b), generated by driving the real
/// `_MOMParseMessageData`/`_MOMProcessEvent`/`createEnumerateDevicesMessage`
/// code paths on Linux and recording the bytes each request produced.
///
/// The C app handler used to generate the fixtures appends `1` and calls
/// sendReply(.success) for any get-request that reaches it, and returns
/// success for notifications — the harness below does the same.
///
/// Options used for generation: deviceID=1, deviceName="DAD-MOM",
/// modelID="710", serialNumber="71000000000",
/// systemTypeAndVersion="710100A   171127", cpufw "cpufw"/"1.0.0.2",
/// recovery "recovery"/"1.0.0.2".
final class MOMWireCompatTests: XCTestCase {
  private static func goldenOptions() -> MOMOptions {
    var o = MOMOptions()
    o.deviceID = 1
    o.deviceName = "DAD-MOM"
    o.modelID = "710"
    o.serialNumber = "71000000000"
    o.systemTypeAndVersion = "710100A   171127"
    o.cpuFirmwareTag = "cpufw"
    o.cpuFirmwareVersion = "1.0.0.2"
    o.recoveryFirmwareTag = "recovery"
    o.recoveryFirmwareVersion = "1.0.0.2"
    return o
  }

  // MARK: - Discovery (`:edev` / `!edev`)

  func testDiscoveryReplyMatchesC() {
    let q = DispatchQueue(label: "wire-compat")
    let c = MOMController(options: Self.goldenOptions(), queue: q,
                          handler: { _, _, _, _, _ in .success })
    let reply = q.sync { MOMDiscovery.discoveryReplyBytes(controller: c, isSolicited: true) }
    XCTAssertEqual(asString(reply),
                   ":edev,0,1,1,'DAD-MOM','710',0,'71000000000'\r")
    let notification = q.sync { MOMDiscovery.discoveryReplyBytes(controller: c, isSolicited: false) }
    XCTAssertEqual(asString(notification),
                   "!edev,0,1,1,'DAD-MOM','710',0,'71000000000'\r")
  }

  // MARK: - Device notifications / replies (encode)

  func testNotificationEncodingMatchesC() {
    assertEncodes(.setKeyState | .typeDeviceNotification, [.int(1), .int(1)],
                  "!skeystate,1,1\r")
    assertEncodes(.setLedState | .typeDeviceNotification, [.int(1), .int(2)],
                  "!sledstate,1,2\r")
    assertEncodes(.setRotationCount | .typeDeviceNotification, [.int(1), .int(-1)],
                  "!srotcount,1,-1\r")
    assertEncodes(.identify | .typeDeviceNotification, [],
                  "!sidentify\r")
    assertEncodes(.setDeviceID | .typeDeviceReply, [.int(2), .string("DAD-MOM2")],
                  ":sdevid,2,'DAD-MOM2'\r")
  }

  // MARK: - Scripted request/reply session

  /// Each step is a raw wire line and the exact bytes the C implementation
  /// sent back (empty = silence). Steps run in order against one controller;
  /// state changes (mastership, sdevid) deliberately carry forward.
  private struct Step {
    let name: String
    let input: Data
    let expected: String
    init(_ name: String, _ input: String, _ expected: String) {
      self.name = name
      self.input = Data(input.utf8)
      self.expected = expected
    }
    init(_ name: String, raw input: Data, _ expected: String) {
      self.name = name
      self.input = input
      self.expected = expected
    }
  }

  private static let session: [Step] = [
    Step("aliverequest", "?aliverequest\r", ":aliverequest,0\r"),
    Step("ghwconf.missing_version", "?ghwconf\r", ":ghwconf,1\r"),
    Step("ghwconf", "?ghwconf,2\r",
         ":ghwconf,0,2,1,'710100A   171127','71000000000'\r"),
    Step("gswver.bad_version", "?gswver,1\r", ":gswver,2,1\r"),
    Step("gswver", "?gswver,2\r",
         ":gswver,0,2,'cpufw','1.0.0.2','recovery','1.0.0.2'\r"),
    Step("gdevinfo", "?gdevinfo\r", ":gdevinfo,0,'710',0,'71000000000'\r"),
    Step("gdevid", "?gdevid\r", ":gdevid,0,1,'DAD-MOM'\r"),
    Step("gip", "?gip\r", ":gip,0,1,'','','',''\r"),
    Step("gmaster.not_master", "?gmaster\r", ":gmaster,0,0\r"),
    Step("galivetime", "?galivetime\r", ":galivetime,0,20\r"),
    Step("salivetime", "&salivetime,20\r", ":salivetime,0,20\r"),
    Step("gkeymode.missing_param", "?gkeymode\r", ":gkeymode,1\r"),
    Step("gkeymode", "?gkeymode,1\r", ":gkeymode,0,1,1,0\r"),
    Step("skeystate.notification_not_master", "%skeystate,1,1\r", ""),
    Step("smaster.wrong_tag", "&smaster,1\r", ""),
    Step("smaster.take", "%smaster,1\r", ""),
    Step("gmaster.is_master", "?gmaster\r", ":gmaster,0,1\r"),
    Step("skeymode.host_set", "&skeymode,1,2\r", ":skeymode,1,1,2\r"),
    Step("gkeystate.app_handler", "?gkeystate,1\r", ":gkeystate,0,1,1\r"),
    Step("gledstate.app_handler", "?gledstate,1\r", ":gledstate,0,1,1\r"),
    Step("gledint.app_handler", "?gledint\r", ":gledint,0,1\r"),
    Step("grotcount.app_handler", "?grotcount\r", ":grotcount,0,1\r"),
    Step("skeystate.host_notification", "%skeystate,1,1\r", ""),
    Step("sledstate.host_notification", "%sledstate,1,2\r", ""),
    Step("sdevid.host_notification", "%sdevid,2,'DAD-MOM2'\r", ""),
    Step("gdevid.after_sdevid", "?gdevid\r", ":gdevid,0,2,'DAD-MOM2'\r"),
    Step("unknown_event", "?bogus\r", "?bogus,0\r"),
    Step("unknown_tag", "*gdevid\r", ""),
    Step("nonascii_leading", raw: Data([0xC4, 0xBF]) + Data("gdevid\r".utf8), ""),
    Step("empty_params_trailing_comma", "?gdevid,\r", ":gdevid,0,2,'DAD-MOM2'\r"),
  ]

  func testScriptedSessionMatchesC() {
    let q = DispatchQueue(label: "wire-compat-session")
    // Mimic the C fixture generator's app handler: get-requests that fall
    // through to it are answered with the params plus a trailing `1`.
    let c = MOMController(options: Self.goldenOptions(), queue: q,
                          handler: { c, peer, evt, params, sendReply in
      if let sendReply {
        return sendReply(c, peer, evt, .success, params + [.int(1)])
      }
      return .success
    })
    let peer = MOMPeerContext.detached(controller: c, peerName: "wire-compat")
    var sent = Data()
    c._sendHook = { _, data in sent.append(data) }

    for step in Self.session {
      sent.removeAll()
      // Mirror the peer read path: decode one line, process host events,
      // enqueue error replies for unknown requests, drop invalid lines.
      switch MOMMessage.decode(step.input) {
      case let .ok(event, params):
        q.sync { _ = c._processEvent(peer: peer, eventWithType: event, params: params) }
      case let .unknownRequest(reply):
        sent.append(reply)
      case .invalid:
        break
      }
      XCTAssertEqual(asString(sent), step.expected,
                     "fixture '\(step.name)' for input \(asString(step.input))")
    }
  }

  // MARK: - Hardware trace (DADman ↔ real MOM, /tmp/ms.txt 2026-06)

  /// Request/reply pairs taken from a packet trace of a real hardware MOM
  /// initialisation. Only built-in-handler exchanges are replayed; values
  /// the app handler supplies on real hardware (led/ring state etc.) are not
  /// asserted here.
  ///
  /// Note: the hardware reports different identifiers in `:ghwconf`
  /// ('7101001806035') and `:gdevinfo` ('71080000062'); MOMOptions has a
  /// single `serialNumber` feeding both handlers (as did the C original), so
  /// the two exchanges are asserted with separately-configured controllers.
  func testHardwareTraceBuiltinReplies() {
    var opts = Self.goldenOptions()
    opts.serialNumber = "71080000062"
    let steps: [Step] = [
      Step("hw.gdevid", "?gdevid\r", ":gdevid,0,1,'DAD-MOM'\r"),
      Step("hw.gkeymode", "?gkeymode,5\r", ":gkeymode,0,5,1,0\r"),
      Step("hw.gmaster", "?gmaster\r", ":gmaster,0,0\r"),
      Step("hw.gdevinfo", "?gdevinfo\r", ":gdevinfo,0,'710',0,'71080000062'\r"),
      Step("hw.smaster", "%smaster,1\r", ""),
      Step("hw.salivetime", "&salivetime,20\r", ":salivetime,0,20\r"),
      Step("hw.aliverequest", "?aliverequest\r", ":aliverequest,0\r"),
    ]
    replay(steps, options: opts)

    var hwconfOpts = Self.goldenOptions()
    hwconfOpts.serialNumber = "7101001806035"
    hwconfOpts.systemTypeAndVersion = "710100A 171127"
    replay([Step("hw.ghwconf", "?ghwconf,2\r",
                 ":ghwconf,0,2,1,'710100A 171127','7101001806035'\r")],
           options: hwconfOpts)
  }

  /// On the wire, key presses are device notifications that reuse the
  /// `gkeystate` event name with an explicit status param (trace line:
  /// `!gkeystate,0,7,1`), not `!skeystate`.
  func testHardwareTraceKeyStateNotificationEncoding() {
    assertEncodes(.getKeyState | .typeDeviceNotification,
                  [.int(0), .int(7), .int(1)],
                  "!gkeystate,0,7,1\r")
  }

  private func replay(_ steps: [Step], options: MOMOptions,
                      file: StaticString = #filePath, line: UInt = #line) {
    let q = DispatchQueue(label: "wire-compat-hw")
    let c = MOMController(options: options, queue: q,
                          handler: { _, _, _, _, _ in .success })
    let peer = MOMPeerContext.detached(controller: c, peerName: "wire-compat-hw")
    var sent = Data()
    c._sendHook = { _, data in sent.append(data) }
    for step in steps {
      sent.removeAll()
      switch MOMMessage.decode(step.input) {
      case let .ok(event, params):
        q.sync { _ = c._processEvent(peer: peer, eventWithType: event, params: params) }
      case let .unknownRequest(reply):
        sent.append(reply)
      case .invalid:
        break
      }
      XCTAssertEqual(asString(sent), step.expected,
                     "fixture '\(step.name)' for input \(asString(step.input))",
                     file: file, line: line)
    }
  }

  // MARK: - Helpers

  private func assertEncodes(_ event: MOMEvent, _ params: [MOMParameter],
                             _ expected: String,
                             file: StaticString = #filePath, line: UInt = #line) {
    let data = MOMMessage.encode(event, params: params)
    XCTAssertNotNil(data, file: file, line: line)
    XCTAssertEqual(asString(data ?? Data()), expected, file: file, line: line)
  }

  /// Render wire bytes losslessly for failure messages (all goldens are ASCII).
  private func asString(_ data: Data) -> String {
    String(decoding: data, as: UTF8.self)
  }
}
